name: Sublime Text Syntax Tests
author: FichteFoll
description: Install and run Sublime Text's syntax test runner
branding:
  icon: check-circle
  color: orange

inputs:
  build:
    description: Build that should be installed. Not all builds are available
    required: false
    default: latest
  default_packages:
    description: Install the default packages and which version (accepts any git ref)
    required: false
    default: false
  default_tests:
    description: Whether to keep the tests of the default packages
    required: false
    default: false
  package_root:
    description: Path to the package root that is linked to the testing Packages folder
    required: false
    default: .
  package_name:
    description: Name to install the package as
    required: false
    default: ${{ github.event.repository.name }}  # github.repository has full name

outputs: {}

runs:
  using: composite
  steps:
    - name: Install dependencies
      # composite steps don't support `if`
      run: |
        if [[ ${{ inputs.build }} < 4077 || ${{ inputs.build }} == 'latest' ]]; then
          sudo apt-get update && sudo apt-get install -y \
            libcairo2 \
            libgl1-mesa-glx \
            libglib2.0-0 \
            libglu1-mesa \
            libgtk-3-0 \
            libpango-1.0-0 \
            libpangocairo-1.0-0;
        fi
      shell: bash
    - name: Download and run syntax tests
      run: ${{ github.action_path }}/syntax-tests.sh
      shell: bash
      env:
        # composite actions don't expose input variables by default for some reason (unlike docker actions)
        INPUT_BUILD: ${{ inputs.build }}
        INPUT_DEFAULT_PACKAGES: ${{ inputs.default_packages }}
        INPUT_DEFAULT_TESTS: ${{ inputs.default_tests }}
        INPUT_PACKAGE_ROOT: ${{ inputs.package_root }}
        INPUT_PACKAGE_NAME: ${{ inputs.package_name }}
