name: Tests

on: [push, pull_request]

jobs:
  no_defpkg:
    name: Test without default packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 4073
          package_root: test/no_defpkg

  defpkg:
    name: Test with default packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 4073
          default_packages: master
          package_root: test/defpkg

  st3:
    name: ST3 build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 3210
          default_packages: st3
          package_root: test/st3

      # This is expected to fail and used to test the error wrapper
      - uses: ./
        continue-on-error: true
        with:
          build: 4073
          default_packages: master
          package_root: test/st3
