name: Tests

on: [push, pull_request]

jobs:
  no_defpkg:
    name: Without default packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 4102
          package_root: test/no_defpkg

  # TODO indentation tests

  defpkg:
    name: With default packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 4102
          default_packages: master
          package_root: test/defpkg

  no_defpkg_old:
    name: Without default packages, old runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 4073
          package_root: test/no_defpkg

  st3:
    name: ST3 build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          build: 3210
          default_packages: st3
          package_root: test/st3

  # This is expected to error and used to test the error wrapper
  st3_error:
    name: Error on purpose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        continue-on-error: true
        with:
          build: 4102
          default_packages: master
          package_root: test/st3
