name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "* 0 * * SAT"
  workflow_dispatch:

jobs:
  no_defpkg:
    name: Without default packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          build: 4189
          package_root: test/no_defpkg

  # TODO indentation tests
  # TODO reference & definition tests

  defpkg:
    name: With default packages, latest stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          build: 4189
          default_packages: master
          package_root: test/defpkg

  no_defpkg_old_build:
    name: Without default packages, old build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          build: 4073
          package_root: test/no_defpkg

  no_defpkg_old_runtime:
    name: Without default packages, latest build, ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          build: latest
          package_root: test/no_defpkg

  third-party:
    name: Third-party
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (primary package)
        uses: actions/checkout@v4
      - name: Checkout INI package (dependency)
        uses: actions/checkout@v4
        with:
          repository: jwortmann/ini-syntax
          ref: v1.5.0
          path: third-party/INI
      - uses: ./
        with:
          build: 4189  # stable
          package_root: test/third-party
          additional_packages: third-party/INI

  dummy_syntax:
    name: Dummy Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (primary package)
        uses: actions/checkout@v4
      - uses: ./
        with:
          build: 4189  # stable
          package_root: test/dummy-syntax
          dummy_syntaxes: text.dummy

  st3:
    name: ST3 build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          build: 3210
          default_packages: v3189
          package_root: test/st3

  # This is expected to error and used to test the error wrapper
  st3_error:
    name: Error on purpose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        continue-on-error: true
        with:
          build: 4189
          default_packages: master
          package_root: test/st3
